project:
  type: website
  output-dir: docs

website:
  title: "Lotte Pohl"
  favicon: images/lotte_logo.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - thesis_updates.qmd
      # - thesis_docs/acoustic_season_sex.qmd
      # - thesis_docs/vertical_data_exploration.qmd
      - href: files/LottePohl_CV_February2023.pdf
        text: cv
      - icon: github # add icons that link to social media, etc.
        href: https://github.com/lottepohl
      - icon: twitter
        href: https://twitter.com/lottepohl
      - icon: linkedin
        href: https://www.linkedin.com/in/lotte-pohl-491315185/
    
# supplying a light ("minty") and dark ("slate") theme to toggle between
format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css
    toc: true

editor: source

